import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,Users,PenLine,Building2,Mail,Palette,ShieldCheck,ScrollText,Settings,Menu,Search,Plus,CheckCircle2,ServerCog} from 'lucide-react';
import './styles.css';

type Page='Dashboard'|'People'|'Departments'|'Email Accounts'|'Signatures'|'Templates'|'Branding'|'Domains'|'Policies'|'Gateway'|'Audit';
const nav:[Page,any][]=[['Dashboard',LayoutDashboard],['People',Users],['Departments',Building2],['Email Accounts',Mail],['Signatures',PenLine],['Templates',ScrollText],['Branding',Palette],['Domains',ShieldCheck],['Policies',Settings],['Gateway',ServerCog],['Audit',ScrollText]];
const stats=[['Employees','3','Active staff'],['Email accounts','3','Managed mailboxes'],['Signatures','3','Published versions'],['Gateway','Online','Last heartbeat 2 min ago']];
function App(){const [page,setPage]=useState<Page>('Dashboard'); const [mobile,setMobile]=useState(false); return <div className="app"><aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><div className="mark">MW</div><div><b>MobiWave</b><span>Signature Manager</span></div></div><nav>{nav.map(([name,Icon])=><button className={page===name?'active':''} onClick={()=>{setPage(name);setMobile(false)}} key={name}><Icon size={17}/>{name}</button>)}</nav><div className="sidefoot"><span>Production</span><small>v1.0.0</small></div></aside><main><header><button className="menu" onClick={()=>setMobile(!mobile)}><Menu/></button><div><div className="eyebrow">MOBIWAVE INNOVATIONS LTD</div><h1>{page}</h1></div><div className="header-actions"><div className="search"><Search size={16}/><input placeholder="Search"/></div><div className="avatar">BM</div></div></header><section className="content">{page==='Dashboard'?<Dashboard/>:<PageView page={page}/>}</section></main></div>}
function Dashboard(){return <><div className="welcome"><div><h2>Signature control centre</h2><p>Manage company signatures centrally and keep every outgoing message consistent.</p></div><button className="primary"><Plus size={16}/> New signature</button></div><div className="stats">{stats.map(s=><div className="stat" key={s[0]}><span>{s[0]}</span><strong>{s[1]}</strong><small>{s[2]}</small></div>)}</div><div className="grid"><div className="panel"><div className="panelhead"><div><h3>Signature coverage</h3><p>Current assignment status</p></div><span className="badge good">Healthy</span></div><div className="coverage"><div><strong>100%</strong><span>managed accounts</span></div><div className="bar"><i/></div></div><div className="rows"><Row n="Brighton Malingi" d="Executive" s="CEO — Default"/><Row n="Preston" d="Sales" s="Corporate — Default"/><Row n="Graham" d="Technical" s="Technical — Default"/></div></div><div className="panel"><div className="panelhead"><div><h3>Gateway</h3><p>Mail injection service</p></div><span className="dot online">Online</span></div><div className="gateway"><CheckCircle2 size={25}/><div><strong>Ready to inject</strong><p>API authentication is configured. Mail continues normally if the signature service is unavailable.</p></div></div><div className="endpoint"><code>POST /api/signatures/resolve</code></div></div></div></>}
function Row({n,d,s}:{n:string,d:string,s:string}){return <div className="row"><div className="person">{n.split(' ').map(x=>x[0]).join('')}</div><div><strong>{n}</strong><small>{d}</small></div><span>{s}</span></div>}
function PageView({page}:{page:Page}){const titles:Record<string,string>={People:'Employees and administrators',Departments:'Organize signature defaults by department', 'Email Accounts':'Managed mailboxes and sender mapping',Signatures:'Published signature definitions',Templates:'Reusable signature layouts',Branding:'Company identity and assets',Domains:'Domains and default routing',Policies:'Injection and reply behaviour',Gateway:'Mail gateway integration',Audit:'Configuration history'}; return <div className="placeholder"><div className="panel"><div className="panelhead"><div><h2>{titles[page]}</h2><p>Production-ready module scaffold with Neon-backed API contracts.</p></div><button className="primary"><Plus size={16}/> Add</button></div>{page==='Signatures'?<SignatureBuilder/>:<div className="empty"><div className="emptyicon">{page==='Gateway'?<ServerCog/>:<PenLine/>}</div><h3>{page} module ready</h3><p>Connect this view to the API and Neon data model. The backend routes and signature engine are included in this release.</p></div>}</div></div>}
function SignatureBuilder(){return <div className="builder"><div><label>Name<input defaultValue="Executive — Brighton"/></label><label>Template<select><option>Executive</option><option>Corporate</option><option>Sales</option><option>Technical</option></select></label><label>HTML signature<textarea defaultValue={'<!-- MW_SIGNATURE_START -->\n<table cellpadding="0" cellspacing="0">\n<tr><td><strong>{{display_name}}</strong></td></tr>\n<tr><td>{{job_title}} · {{company_name}}</td></tr>\n<tr><td>{{email}} · {{phone}}</td></tr>\n<tr><td><a href="https://mobiwave.co.ke">mobiwave.co.ke</a></td></tr>\n</table>\n<!-- MW_SIGNATURE_END -->'} /></label></div><div className="preview"><span>LIVE PREVIEW</span><div className="previewbox"><strong>Brighton Malingi</strong><br/>Chief Executive Officer · MobiWave Innovations Ltd<br/>brighton@mobiwave.co.ke · +254 736 427 842<br/><a href="https://mobiwave.co.ke">mobiwave.co.ke</a></div></div></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
